# Generated by Django 4.2.5 on 2024-05-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField()),
                ('title', models.TextField()),
                ('content', models.TextField(blank=True)),
                ('route', models.TextField(blank=True)),
                ('event', models.TextField(blank=True)),
                ('webSiteId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FrameElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField()),
                ('type', models.TextField()),
                ('frameId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WebSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
            ],
        ),
    ]
